name: Prueba V6 Bluetooth

on:
  workflow_dispatch:

jobs:
  prueba:
    runs-on: ubuntu-latest

    steps:
      - name: Comprobar GitHub Actions
        run: |
          echo "GitHub Actions funciona correctamente"
          echo "Prueba V6 Bluetooth"